[build]
  publish = "client/"

# we can do this with physical sub folders
# [[redirects]]
#  from = "/en/*"
#  to = "/en/index.html"
#  status = 200


[[redirects]]
  from = "/en/*"
  to = "/index.en.html"
  status = 200

[[redirects]]
  from = "/ar/*"
  to = "/index.ar.html"
  status = 200

[[redirects]]
  from = "/fr/*"
  to = "/index.fr.html"
  status = 200


# if nothing matches redirect root to language cookie

[[redirects]]
  from = "/*"
  to = "/ar/"
  status = 301
  conditions = {Language = ["ar"]}

[[redirects]]
  from = "/*"
  to = "/fr/"
  status = 301
  conditions = {Language = ["fr"]}


# default redirect
[[redirects]]
  from = "/*"
  to = "/en/"
  status = 301

